name: Felixius
favicon: null
layout_spectrum: 0.4279775589238852
typography_spectrum: 0.98748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.81750030326657
  lightness: 0.25
  saturation: 0.07097783754579723
  rhythmicContrast: 0.8341910615563393
purpose: []
